configfile: "config/config.yaml"

# stuff primarily associated with figure 1 and related supp materials
include: "rules/make_resources.smk"
include: "rules/exploratory_and_descriptive.smk"
include: "rules/coexpression_replication.smk"
include: "rules/te_sequence_similarity.smk"
include: "rules/rankings.smk"
include: "rules/enrichment.smk"
include: "rules/differential_expression.smk"
include: "rules/motifs.smk"
include: "rules/motifs_unr.smk"
include: "rules/signatures.smk"
include: "rules/phylosignal.smk"
include: "rules/pirna.smk"
include: "rules/csem_mosaics.smk"
include: "rules/ripseq.smk"
include: "rules/scrna.smk"
include: "rules/figures.smk"
include: "rules/supplementary_tables.smk"
include: "rules/motifs_cg16779.smk"

rule all:
    input:
        rules.figures.input,
        rules.figures.output,
        rules.supp_figures.output,  
        rules.figuredata.output,
        rules.tables.input,

