configfile: "config/config.yaml"

# stuff primarily associated with figure 1 and related supp materials
include: "rules/make_resources.smk"
include: "rules/exploratory_and_descriptive.smk"
include: "rules/coexpression_replication.smk"
include: "rules/te_sequence_similarity.smk"
include: "rules/rankings.smk"
include: "rules/enrichment.smk"
include: "rules/differential_expression.smk"
include: "rules/motifs.smk"
include: "rules/motifs_unr.smk"
include: "rules/signatures.smk"
include: "rules/zad_phylo.smk"
include: "rules/phylosignal.smk"
include: "rules/scrna.smk"
include: "rules/repetitiveness.smk"
include: "rules/pirna.smk"
include: "rules/csem_mosaics.smk"
include: "rules/other_plots.smk"
include: "rules/stats.smk"
include: "rules/ripseq.smk"
include: "rules/figures.smk"
include: "rules/supplementary_tables.smk"

rule all:
    input:
        rules.figures.output,
        rules.figuredata.output,
        rules.tables.output,




# include: "rules/single-cell-rna.smk"
# include: "rules/rankings.smk"
# include: "rules/enrichment.smk"
# include: "rules/differential_expression.smk"
# include: "rules/signatures.smk"
# # include: "rules/direct_binding.smk"
# include: "rules/rewiring.smk"
# include: "rules/motifs.smk"
# include: "rules/specific_genes.smk"
# include: "rules/ine1.smk"
# include: "rules/stats.smk"
# include: "rules/figures.smk"

