"depends on file generated by an explorator script: workflow/scripts/csem_mosaics/find_bound_fixed_ins.R,
which spits out an rds file to resources/
if substantial changes are made to upstream analyses, find_bound_fixed_ins.R 
should be re-rerun and its outputs inspected"

library(tidyverse)
library(plotgardener)
library(patchwork)
library(plyranges)
# some plotting functions that are quite long - want to keep the figure
# scripts relatively readable where feasible
source("workflow/scripts/utils/plotting.R")

bound_ins <- read_rds("resources/putatively_bound_insertions.rds")

# broad views of the putatively bound insertions
broad_roi <- bound_ins |>
  anchor_center() |>
  mutate(width=12000) 

# fun to get each edge of the insertions
prep_region <- function(x) {
  z <- anchor_center(x) |> mutate(width=50)
  
  split(z,1:length(z))
} 


# get plots
nms <- paste(bound_ins$te,as.character(bound_ins))
wide <- split(broad_roi, 1:length(broad_roi)) |> map(plot_region_signal)  |> set_names(nms)
lefts <- plyranges::flank_left(bound_ins, width = 1) |> prep_region() |> map(possibly_plot_region_reads) |> set_names(nms)
rights <- plyranges::flank_right(bound_ins, width = 1) |> prep_region() |> map(possibly_plot_region_reads) |> set_names(nms)

# best
#wide$`invader2 3R:1412850-1413154`
#lefts$`invader2 3R:1412850-1413154`
#rights$`invader2 3R:1412850-1413154`

plts <- names(wide) |>
  set_names() |>
  map(~{
    list(wide=wide[[.x]],
         left = lefts[[.x]],
         rights = rights[[.x]])
  })

# turn Tracks objkect into ggplot
make_gg <- \(x) ggplotify::as.ggplot(as(x,"grob"))

theme_set(theme_bw() + 
            theme(text = element_text(size=7)) +
            theme(plot.title = element_text(hjust = 0.5))
)

dir.create("results/figures/exemplary_bound_loci")

pdf("results/figures/exemplary_bound_loci/exemplary_bound_locus_1.pdf",width = 8.5, height = 11)

pageCreate(height = 11, showGuides=interactive())

plotText("A", x = 0.5, y=0.5)
plotGG(make_gg(plts$`invader2 3R:1412850-1413154`$wide), x = 0.5, y=0.75, width = 7.5,height = 4)

plotGG(make_gg(plts$`invader2 3R:1412850-1413154`$left), x = 0.5, y=5.25, width = 3.75,height = 5)
plotText("B", x = 0.5, y=5.125)

plotGG(make_gg(plts$`invader2 3R:1412850-1413154`$rights), x = 4.5, y=5.25, width = 3.75,height = 5)
plotText("C", x = 4.5, y=5.125)

dev.off()

