# Rules in this file should create tsv files that hold various rankings of host genes
rule rankings:
    input:
        mods = config.get("MERGED_MODELS"),
        reps = config.get("INDEPENDENT_DATASET"),
    output:
        sig_reps_female_mean_estimate_qnorm = "results/rankings/sig_reps_female_mean_estimate_qnorm.tsv.gz",
        nofilt_reps_female_mean_estimate_qnorm = "results/rankings/nofilt_reps_female_mean_estimate_qnorm.tsv.gz",
        sig_main_female_mean_estimate_qnorm= "results/rankings/sig_main_female_mean_estimate_qnorm.tsv.gz",
        nofilt_main_female_mean_estimate_qnorm= "results/rankings/nofilt_main_female_mean_estimate_qnorm.tsv.gz",
        sig_reps_male_mean_estimate_qnorm= "results/rankings/sig_reps_male_mean_estimate_qnorm.tsv.gz",
        nofilt_reps_male_mean_estimate_qnorm = "results/rankings/nofilt_reps_male_mean_estimate_qnorm.tsv.gz",
        sig_main_male_mean_estimate_qnorm= "results/rankings/sig_main_male_mean_estimate_qnorm.tsv.gz",
        nofilt_main_male_mean_estimate_qnorm= "results/rankings/nofilt_main_male_mean_estimate_qnorm.tsv.gz",
        sig_reps_female_mean_abs_estimate_qnorm= "results/rankings/sig_reps_female_mean_abs_estimate_qnorm.tsv.gz",
        nofilt_reps_female_mean_abs_estimate_qnorm= "results/rankings/nofilt_reps_female_mean_abs_estimate_qnorm.tsv.gz",
        sig_main_female_mean_abs_estimate_qnorm= "results/rankings/sig_main_female_mean_abs_estimate_qnorm.tsv.gz",
        nofilt_main_female_mean_abs_estimate_qnorm= "results/rankings/nofilt_main_female_mean_abs_estimate_qnorm.tsv.gz",
        sig_reps_male_mean_abs_estimate_qnorm= "results/rankings/sig_reps_male_mean_abs_estimate_qnorm.tsv.gz",
        nofilt_reps_male_mean_abs_estimate_qnorm= "results/rankings/nofilt_reps_male_mean_abs_estimate_qnorm.tsv.gz",
        nofilt_main_male_mean_abs_estimate_qnorm= "results/rankings/nofilt_main_male_mean_abs_estimate_qnorm.tsv.gz",
        sig_main_male_mean_abs_estimate_qnorm="results/rankings/sig_main_male_mean_abs_estimate_qnorm.tsv.gz",
        sig_reps_female_max_estimate_qnorm = "results/rankings/sig_reps_female_max_estimate_qnorm.tsv.gz",
        nofilt_reps_female_max_estimate_qnorm = "results/rankings/nofilt_reps_female_max_estimate_qnorm.tsv.gz",
        sig_main_female_max_estimate_qnorm= "results/rankings/sig_main_female_max_estimate_qnorm.tsv.gz",
        nofilt_main_female_max_estimate_qnorm= "results/rankings/nofilt_main_female_max_estimate_qnorm.tsv.gz",
        sig_reps_male_max_estimate_qnorm= "results/rankings/sig_reps_male_max_estimate_qnorm.tsv.gz",
        nofilt_reps_male_max_estimate_qnorm = "results/rankings/nofilt_reps_male_max_estimate_qnorm.tsv.gz",
        sig_main_male_max_estimate_qnorm= "results/rankings/sig_main_male_max_estimate_qnorm.tsv.gz",
        nofilt_main_male_max_estimate_qnorm= "results/rankings/nofilt_main_male_max_estimate_qnorm.tsv.gz",
        sig_reps_female_max_abs_estimate_qnorm= "results/rankings/sig_reps_female_max_abs_estimate_qnorm.tsv.gz",
        nofilt_reps_female_max_abs_estimate_qnorm= "results/rankings/nofilt_reps_female_max_abs_estimate_qnorm.tsv.gz",
        sig_main_female_max_abs_estimate_qnorm= "results/rankings/sig_main_female_max_abs_estimate_qnorm.tsv.gz",
        nofilt_main_female_max_abs_estimate_qnorm= "results/rankings/nofilt_main_female_max_abs_estimate_qnorm.tsv.gz",
        sig_reps_male_max_abs_estimate_qnorm= "results/rankings/sig_reps_male_max_abs_estimate_qnorm.tsv.gz",
        nofilt_reps_male_max_abs_estimate_qnorm= "results/rankings/nofilt_reps_male_max_abs_estimate_qnorm.tsv.gz",
        nofilt_main_male_max_abs_estimate_qnorm= "results/rankings/nofilt_main_male_max_abs_estimate_qnorm.tsv.gz",
        sig_main_male_max_abs_estimate_qnorm="results/rankings/sig_main_male_max_abs_estimate_qnorm.tsv.gz",
         
        sig_reps_female_sum_estimate_qnorm = "results/rankings/sig_reps_female_sum_estimate_qnorm.tsv.gz",
        nofilt_reps_female_sum_estimate_qnorm = "results/rankings/nofilt_reps_female_sum_estimate_qnorm.tsv.gz",
        sig_main_female_sum_estimate_qnorm= "results/rankings/sig_main_female_sum_estimate_qnorm.tsv.gz",
        nofilt_main_female_sum_estimate_qnorm= "results/rankings/nofilt_main_female_sum_estimate_qnorm.tsv.gz",
        sig_reps_male_sum_estimate_qnorm= "results/rankings/sig_reps_male_sum_estimate_qnorm.tsv.gz",
        nofilt_reps_male_sum_estimate_qnorm = "results/rankings/nofilt_reps_male_sum_estimate_qnorm.tsv.gz",
        sig_main_male_sum_estimate_qnorm= "results/rankings/sig_main_male_sum_estimate_qnorm.tsv.gz",
        nofilt_main_male_sum_estimate_qnorm= "results/rankings/nofilt_main_male_sum_estimate_qnorm.tsv.gz",
        sig_reps_female_sum_abs_estimate_qnorm= "results/rankings/sig_reps_female_sum_abs_estimate_qnorm.tsv.gz",
        nofilt_reps_female_sum_abs_estimate_qnorm= "results/rankings/nofilt_reps_female_sum_abs_estimate_qnorm.tsv.gz",
        sig_main_female_sum_abs_estimate_qnorm= "results/rankings/sig_main_female_sum_abs_estimate_qnorm.tsv.gz",
        nofilt_main_female_sum_abs_estimate_qnorm= "results/rankings/nofilt_main_female_sum_abs_estimate_qnorm.tsv.gz",
        sig_reps_male_sum_abs_estimate_qnorm= "results/rankings/sig_reps_male_sum_abs_estimate_qnorm.tsv.gz",
        nofilt_reps_male_sum_abs_estimate_qnorm= "results/rankings/nofilt_reps_male_sum_abs_estimate_qnorm.tsv.gz",
        nofilt_main_male_sum_abs_estimate_qnorm= "results/rankings/nofilt_main_male_sum_abs_estimate_qnorm.tsv.gz",
        sig_main_male_sum_abs_estimate_qnorm="results/rankings/sig_main_male_sum_abs_estimate_qnorm.tsv.gz",

        sig_reps_female_min_estimate_qnorm = "results/rankings/sig_reps_female_min_estimate_qnorm.tsv.gz",
        nofilt_reps_female_min_estimate_qnorm = "results/rankings/nofilt_reps_female_min_estimate_qnorm.tsv.gz",
        sig_main_female_min_estimate_qnorm= "results/rankings/sig_main_female_min_estimate_qnorm.tsv.gz",
        nofilt_main_female_min_estimate_qnorm= "results/rankings/nofilt_main_female_min_estimate_qnorm.tsv.gz",
        sig_reps_male_min_estimate_qnorm= "results/rankings/sig_reps_male_min_estimate_qnorm.tsv.gz",
        nofilt_reps_male_min_estimate_qnorm = "results/rankings/nofilt_reps_male_min_estimate_qnorm.tsv.gz",
        sig_main_male_min_estimate_qnorm= "results/rankings/sig_main_male_min_estimate_qnorm.tsv.gz",
        nofilt_main_male_min_estimate_qnorm= "results/rankings/nofilt_main_male_min_estimate_qnorm.tsv.gz",
        sig_reps_female_min_abs_estimate_qnorm= "results/rankings/sig_reps_female_min_abs_estimate_qnorm.tsv.gz",
        nofilt_reps_female_min_abs_estimate_qnorm= "results/rankings/nofilt_reps_female_min_abs_estimate_qnorm.tsv.gz",
        sig_main_female_min_abs_estimate_qnorm= "results/rankings/sig_main_female_min_abs_estimate_qnorm.tsv.gz",
        nofilt_main_female_min_abs_estimate_qnorm= "results/rankings/nofilt_main_female_min_abs_estimate_qnorm.tsv.gz",
        sig_reps_male_min_abs_estimate_qnorm= "results/rankings/sig_reps_male_min_abs_estimate_qnorm.tsv.gz",
        nofilt_reps_male_min_abs_estimate_qnorm= "results/rankings/nofilt_reps_male_min_abs_estimate_qnorm.tsv.gz",
        nofilt_main_male_min_abs_estimate_qnorm= "results/rankings/nofilt_main_male_min_abs_estimate_qnorm.tsv.gz",
        sig_main_male_min_abs_estimate_qnorm="results/rankings/sig_main_male_min_abs_estimate_qnorm.tsv.gz",

        sig_reps_female_mean_var_exp_x = "results/rankings/sig_reps_female_mean_var_exp_x.tsv.gz",
        nofilt_reps_female_mean_var_exp_x = "results/rankings/nofilt_reps_female_mean_var_exp_x.tsv.gz",
        sig_main_female_mean_var_exp_x= "results/rankings/sig_main_female_mean_var_exp_x.tsv.gz",
        nofilt_main_female_mean_var_exp_x= "results/rankings/nofilt_main_female_mean_var_exp_x.tsv.gz",
        sig_reps_male_mean_var_exp_x= "results/rankings/sig_reps_male_mean_var_exp_x.tsv.gz",
        nofilt_reps_male_mean_var_exp_x = "results/rankings/nofilt_reps_male_mean_var_exp_x.tsv.gz",
        sig_main_male_mean_var_exp_x= "results/rankings/sig_main_male_mean_var_exp_x.tsv.gz",
        nofilt_main_male_mean_var_exp_x= "results/rankings/nofilt_main_male_mean_var_exp_x.tsv.gz",
        sig_reps_female_mean_signed_var_exp_x= "results/rankings/sig_reps_female_mean_signed_var_exp_x.tsv.gz",
        nofilt_reps_female_mean_signed_var_exp_x= "results/rankings/nofilt_reps_female_mean_signed_var_exp_x.tsv.gz",
        sig_main_female_mean_signed_var_exp_x= "results/rankings/sig_main_female_mean_signed_var_exp_x.tsv.gz",
        nofilt_main_female_mean_signed_var_exp_x= "results/rankings/nofilt_main_female_mean_signed_var_exp_x.tsv.gz",
        sig_reps_male_mean_signed_var_exp_x= "results/rankings/sig_reps_male_mean_signed_var_exp_x.tsv.gz",
        nofilt_reps_male_mean_signed_var_exp_x= "results/rankings/nofilt_reps_male_mean_signed_var_exp_x.tsv.gz",
        nofilt_main_male_mean_signed_var_exp_x= "results/rankings/nofilt_main_male_mean_signed_var_exp_x.tsv.gz",
        sig_main_male_mean_signed_var_exp_x="results/rankings/sig_main_male_mean_signed_var_exp_x.tsv.gz",
        sig_reps_female_max_var_exp_x = "results/rankings/sig_reps_female_max_var_exp_x.tsv.gz",
        nofilt_reps_female_max_var_exp_x = "results/rankings/nofilt_reps_female_max_var_exp_x.tsv.gz",
        sig_main_female_max_var_exp_x= "results/rankings/sig_main_female_max_var_exp_x.tsv.gz",
        nofilt_main_female_max_var_exp_x= "results/rankings/nofilt_main_female_max_var_exp_x.tsv.gz",
        sig_reps_male_max_var_exp_x= "results/rankings/sig_reps_male_max_var_exp_x.tsv.gz",
        nofilt_reps_male_max_var_exp_x = "results/rankings/nofilt_reps_male_max_var_exp_x.tsv.gz",
        sig_main_male_max_var_exp_x= "results/rankings/sig_main_male_max_var_exp_x.tsv.gz",
        nofilt_main_male_max_var_exp_x= "results/rankings/nofilt_main_male_max_var_exp_x.tsv.gz",
        sig_reps_female_max_signed_var_exp_x= "results/rankings/sig_reps_female_max_signed_var_exp_x.tsv.gz",
        nofilt_reps_female_max_signed_var_exp_x= "results/rankings/nofilt_reps_female_max_signed_var_exp_x.tsv.gz",
        sig_main_female_max_signed_var_exp_x= "results/rankings/sig_main_female_max_signed_var_exp_x.tsv.gz",
        nofilt_main_female_max_signed_var_exp_x= "results/rankings/nofilt_main_female_max_signed_var_exp_x.tsv.gz",
        sig_reps_male_max_signed_var_exp_x= "results/rankings/sig_reps_male_max_signed_var_exp_x.tsv.gz",
        nofilt_reps_male_max_signed_var_exp_x= "results/rankings/nofilt_reps_male_max_signed_var_exp_x.tsv.gz",
        nofilt_main_male_max_signed_var_exp_x= "results/rankings/nofilt_main_male_max_signed_var_exp_x.tsv.gz",
        sig_main_male_max_signed_var_exp_x="results/rankings/sig_main_male_max_signed_var_exp_x.tsv.gz",


        sig_reps_female_sum_var_exp_x = "results/rankings/sig_reps_female_sum_var_exp_x.tsv.gz",
        nofilt_reps_female_sum_var_exp_x = "results/rankings/nofilt_reps_female_sum_var_exp_x.tsv.gz",
        sig_main_female_sum_var_exp_x= "results/rankings/sig_main_female_sum_var_exp_x.tsv.gz",
        nofilt_main_female_sum_var_exp_x= "results/rankings/nofilt_main_female_sum_var_exp_x.tsv.gz",
        sig_reps_male_sum_var_exp_x= "results/rankings/sig_reps_male_sum_var_exp_x.tsv.gz",
        nofilt_reps_male_sum_var_exp_x = "results/rankings/nofilt_reps_male_sum_var_exp_x.tsv.gz",
        sig_main_male_sum_var_exp_x= "results/rankings/sig_main_male_sum_var_exp_x.tsv.gz",
        nofilt_main_male_sum_var_exp_x= "results/rankings/nofilt_main_male_sum_var_exp_x.tsv.gz",
        sig_reps_female_sum_signed_var_exp_x= "results/rankings/sig_reps_female_sum_signed_var_exp_x.tsv.gz",
        nofilt_reps_female_sum_signed_var_exp_x= "results/rankings/nofilt_reps_female_sum_signed_var_exp_x.tsv.gz",
        sig_main_female_sum_signed_var_exp_x= "results/rankings/sig_main_female_sum_signed_var_exp_x.tsv.gz",
        nofilt_main_female_sum_signed_var_exp_x= "results/rankings/nofilt_main_female_sum_signed_var_exp_x.tsv.gz",
        sig_reps_male_sum_signed_var_exp_x= "results/rankings/sig_reps_male_sum_signed_var_exp_x.tsv.gz",
        nofilt_reps_male_sum_signed_var_exp_x= "results/rankings/nofilt_reps_male_sum_signed_var_exp_x.tsv.gz",
        nofilt_main_male_sum_signed_var_exp_x= "results/rankings/nofilt_main_male_sum_signed_var_exp_x.tsv.gz",
        sig_main_male_sum_signed_var_exp_x="results/rankings/sig_main_male_sum_signed_var_exp_x.tsv.gz",

        sig_reps_female_min_var_exp_x = "results/rankings/sig_reps_female_min_var_exp_x.tsv.gz",
        nofilt_reps_female_min_var_exp_x = "results/rankings/nofilt_reps_female_min_var_exp_x.tsv.gz",
        sig_main_female_min_var_exp_x= "results/rankings/sig_main_female_min_var_exp_x.tsv.gz",
        nofilt_main_female_min_var_exp_x= "results/rankings/nofilt_main_female_min_var_exp_x.tsv.gz",
        sig_reps_male_min_var_exp_x= "results/rankings/sig_reps_male_min_var_exp_x.tsv.gz",
        nofilt_reps_male_min_var_exp_x = "results/rankings/nofilt_reps_male_min_var_exp_x.tsv.gz",
        sig_main_male_min_var_exp_x= "results/rankings/sig_main_male_min_var_exp_x.tsv.gz",
        nofilt_main_male_min_var_exp_x= "results/rankings/nofilt_main_male_min_var_exp_x.tsv.gz",
        sig_reps_female_min_signed_var_exp_x= "results/rankings/sig_reps_female_min_signed_var_exp_x.tsv.gz",
        nofilt_reps_female_min_signed_var_exp_x= "results/rankings/nofilt_reps_female_min_signed_var_exp_x.tsv.gz",
        sig_main_female_min_signed_var_exp_x= "results/rankings/sig_main_female_min_signed_var_exp_x.tsv.gz",
        nofilt_main_female_min_signed_var_exp_x= "results/rankings/nofilt_main_female_min_signed_var_exp_x.tsv.gz",
        sig_reps_male_min_signed_var_exp_x= "results/rankings/sig_reps_male_min_signed_var_exp_x.tsv.gz",
        nofilt_reps_male_min_signed_var_exp_x= "results/rankings/nofilt_reps_male_min_signed_var_exp_x.tsv.gz",
        nofilt_main_male_min_signed_var_exp_x= "results/rankings/nofilt_main_male_min_signed_var_exp_x.tsv.gz",
        sig_main_male_min_signed_var_exp_x="results/rankings/sig_main_male_min_signed_var_exp_x.tsv.gz",


        
    script:
        "../scripts/rankings/rankings.R"